### ISSUE TITLE
URLs take up the limit

### ISSUE THREAD

**Issue by FunkedelicBob** [markviews/GmailWebhook#1]
Thanks for putting this together, it works **really** well! The problem I'm running into is so many emails will have href URLs, which are often huge (because of all the cookie and tracking information baked into them). Do you know of a quick way to filter out URLs from showing up in the output?

**Comment by markviews** [comment]
oh i didn't think about that.

Yeah add this line right above line `105`
```javascript
body = body.replace(/(?:https?|ftp):\/\/[\n\S]+/g, '[Link]');
```

I got this regex from [here](https://stackoverflow.com/a/23571059/3184295) for anyone wondering.

**Comment by FunkedelicBob** [comment]
Blarg! I was just coming back to say that I tried the regex below in line 82, but I still couldn't get it to work. And lo and behold you had already responded! I was on the right track :P Thanks so much!

`.replace(/(?:https?|ftp):\/\/[\n\S]+/g, '')`

**Comment by justinbarcelos** [comment]
Actually, for anyone else who sees this, do put it on line `105` like @markviews mentioned, but use the code below. The other one works, but strips all formatting (it's just raw html). This will do the trick:

`body = body.replace(/(?:https?|ftp):\/\/[\n\S]+/g, '');`
